name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.8.0
  provider: ^6.1.2
  routing_generator:
    git: https://github.com/JonathanVegasP/routing_generator.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  routing_generator_builder:
    git: https://github.com/JonathanVegasP/routing_generator_builder.git

flutter:
  uses-material-design: true
